from abc import ABC, abstractmethod

import game


class Agent(ABC):
    def get_action(self, state: game.State) -> game.PlayerAction:
        raise NotImplementedError


hard_table = {
    4: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    5: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    6: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    7: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    8: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    9: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    10: {
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    11: {
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.DOUBLE,
        11: game.PlayerAction.HIT,
    },
    12: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    13: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    14: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    15: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    16: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    17: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    18: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    19: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    20: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    21: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    }
}
soft_table = {
    13: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    14: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    15: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    16: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    17: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    18: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    19: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    20: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    21: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
}
split_table = {
    2: {
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.SPLIT,
        11: game.PlayerAction.SPLIT,
    },
    4: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    6: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    8: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    10: {
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    12: {
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    14: {
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
        11: game.PlayerAction.HIT,
    },
    16: {
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.SPLIT,
        11: game.PlayerAction.SPLIT,
    },
    18: {
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    },
    20: {
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
        11: game.PlayerAction.STAND,
    }
}

class BasicStrategyAgent(Agent):
    def get_action(self, state: game.State) -> game.PlayerAction:
        if state.hand_kind == game.HandKind.HARD:
            return hard_table[state.player_total[-1]][state.dealer_number]
        if state.hand_kind == game.HandKind.SOFT:
            return soft_table[state.player_total[-1]][state.dealer_number]
        if state.hand_kind == game.HandKind.PAIR:
            return split_table[state.player_total[-1]][state.dealer_number]
