from abc import ABC

import game


class Agent(ABC):
    def get_action(self, state: game.State) -> game.PlayerAction:
        raise NotImplementedError


hard_table = {
    2: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    3: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    4: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    5: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    6: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    7: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    8: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    9: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    10: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.HIT,
    },
    11: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.DOUBLE,
    },
    12: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    13: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    14: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    15: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    16: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    17: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    18: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    19: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    20: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    21: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
}
soft_table = {
    11: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    12: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    13: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    14: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    15: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    16: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    17: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    18: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    19: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    20: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
    21: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
}
split_table = {
    2: {
        1: game.PlayerAction.SPLIT,
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.SPLIT,
    },
    4: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    6: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    8: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.HIT,
        4: game.PlayerAction.HIT,
        5: game.PlayerAction.HIT,
        6: game.PlayerAction.HIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    10: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.DOUBLE,
        3: game.PlayerAction.DOUBLE,
        4: game.PlayerAction.DOUBLE,
        5: game.PlayerAction.DOUBLE,
        6: game.PlayerAction.DOUBLE,
        7: game.PlayerAction.DOUBLE,
        8: game.PlayerAction.DOUBLE,
        9: game.PlayerAction.DOUBLE,
        10: game.PlayerAction.HIT,
    },
    12: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.HIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.HIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    14: {
        1: game.PlayerAction.HIT,
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.HIT,
        9: game.PlayerAction.HIT,
        10: game.PlayerAction.HIT,
    },
    16: {
        1: game.PlayerAction.SPLIT,
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.SPLIT,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.SPLIT,
    },
    18: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.SPLIT,
        3: game.PlayerAction.SPLIT,
        4: game.PlayerAction.SPLIT,
        5: game.PlayerAction.SPLIT,
        6: game.PlayerAction.SPLIT,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.SPLIT,
        9: game.PlayerAction.SPLIT,
        10: game.PlayerAction.STAND,
    },
    20: {
        1: game.PlayerAction.STAND,
        2: game.PlayerAction.STAND,
        3: game.PlayerAction.STAND,
        4: game.PlayerAction.STAND,
        5: game.PlayerAction.STAND,
        6: game.PlayerAction.STAND,
        7: game.PlayerAction.STAND,
        8: game.PlayerAction.STAND,
        9: game.PlayerAction.STAND,
        10: game.PlayerAction.STAND,
    },
}

basic_strategy = {
    game.HandKind.HARD: hard_table,
    game.HandKind.SOFT: soft_table,
    game.HandKind.PAIR: split_table,
}


class BasicStrategyAgent(Agent):
    def get_action(self, state: game.State) -> game.PlayerAction:
        try:
            action = basic_strategy[state.hand_kind][state.player_total[-1]][
                state.dealer_number
            ]
        except KeyError:
            print(f"state: {state}")
            print(f"state.hand_kind: {state.hand_kind}")
            print(f"state.player_total[-1]: {state.player_total[-1]}")
            raise KeyError
        if (
            action == game.PlayerAction.DOUBLE
            and action not in state.action_range
        ):
            action = game.PlayerAction.HIT

        return action
